package com.triadss.doctrack2.config.constants;

public class ReportConstants {
    public static String ACCEPTED_APPOINTMENT = "ACCEPTED APPOINTMENT";
    public static String REJECTED_APPOINTMENT = "REJECTED APPOINTMENT";
    public static String CANCELLED_APPOINTMENT = "CANCELLED APPOINTMENT";
    public static String RESCHEDULED_APPOINTMENT = "RESCHEDULED APPOINTMENT";
    public static String ADDED_PATIENT = "ADDED PATIENT";
    public static String ADDED_PATIENT_MEDICAL_HISTORY = "ADDED PATIENT MEDICAL HISTORY";
    public static String ADDED_PATIENT_VITAL_SIGNS = "ADDED PATIENT VITAL SIGNS";
    public static String ADDED_PATIENT_MEDICATION = "ADDED PATIENT MEDICATION";
    public static String REMOVED_PATIENT_MEDICATION = "REMOVED PATIENT MEDICATION";
    public static String UPDATED_PATIENT_INFO = "UPDATED PATIENT INFO";
    public static String UPDATED_PATIENT_MEDICAL_HISTORY = "UPDATED PATIENT MEDICAL HISTORY";
    public static String UPDATED_PATIENT_VITAL_SIGNS = "UPDATED PATIENT VITAL SIGNS";
    public static String REQUESTED_APPOINTMENT = "REQUESTED APPOINTMENT";
    public static String ADDED_MEDICATION = "ADDED MEDICATION";
    public static String COMPLETED_MEDICATION = "COMPLETED MEDICATION";
    public static String UPDATED_MEDICATION = "UPDATED MEDICATION";

    public static String[] HEALTHPROF_APPOINTMENT_REPORTS = new String[]{
        ACCEPTED_APPOINTMENT,
        REJECTED_APPOINTMENT,
        CANCELLED_APPOINTMENT,
        RESCHEDULED_APPOINTMENT
    };

    public static String[] HEALTHPROF_PATIENT_REPORTS = new String[]{
        ADDED_PATIENT,
        ADDED_PATIENT_MEDICAL_HISTORY,
        ADDED_PATIENT_VITAL_SIGNS,
        ADDED_PATIENT_MEDICATION,
        REMOVED_PATIENT_MEDICATION,
        UPDATED_PATIENT_INFO,
        UPDATED_PATIENT_MEDICAL_HISTORY,
        UPDATED_PATIENT_VITAL_SIGNS
    };

    public static String[] PATIENT_APPOINTMENT_REPORTS = new String[]{
        REQUESTED_APPOINTMENT,
        CANCELLED_APPOINTMENT,
        RESCHEDULED_APPOINTMENT
    };

    public static String[] PATIENT_MEDICATION_REPORTS = new String[]{
            ADDED_MEDICATION,
            COMPLETED_MEDICATION,
            UPDATED_MEDICATION
    };
}